server:
  port: ${BACKEND_PORT}

spring:
  application:
    name: cashflow
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none
  graphql:
    graphiql:
      enabled: true